# This is a basic workflow to help you get started with Actions

name: dir

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - uses: qoomon/actions--setup-git@v1
        with:
          user: bot

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          echo `pwd`
          find . -regextype sed -regex "\./[0-9]\{4\}/\(mdModule\|index\)\.md" | sort
          grep -H -e "^# _Module.*_" -e "^title:\s*\"Module.*\"" `find . -regextype sed -regex "\./[0-9]\{4\}/\(mdModule\|index\)\.md" | sort` > directory.txt
          cat directory.txt | sed -e "s/^\(.*\):\(#\s*_\|title:\s*\"\)\(.*\)\([_\|\"]\)/* [\3](\1)/" > directory1.md
          if ! diff -q directory.md directory1.md; then
            mv directory1.md directory.md
            git add directory.md
            git add directory.txt
            git commit -m "generated"
            git push
          fi
      # - uses: jeffreytse/jekyll-deploy-action@master
      #  with:
      #    provider: 'github'
      #    token: ${{ secrets.GITHUB_TOKEN }}
          
      # update repository
      
